# Default Configuration for NeuroSymbolic-Recursive Training

# Model architecture
model:
  input_dim: 16
  hidden_dim: 128
  output_dim: 9
  dropout: 0.1

# Data configuration
data:
  num_samples: 10000
  train_split: 0.8
  batch_size: 32

# Training parameters
training:
  num_epochs: 20
  learning_rate: 0.001
  weight_decay: 0.0001
  num_refinement_steps: 3
  checkpoint_freq: 5

# Refinement configuration
refinement:
  max_iterations: 5
  confidence_threshold: 0.9
  convergence_tolerance: 0.01

# System configuration
system:
  seed: 42
  use_gpu: true
  log_level: "INFO"
  num_workers: 4